/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//#define MCU_Act_As_Master
#define MCU_Act_As_Slave

#include "stm32_f103x6.h"
#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_exti_driver.h"
#include "Stm32_F103C6_USART_driver.h"
#include "Stm32_F103C6_SPI_driver.h"

//***************************************************************************************
//			Terminal1 <-----> USART1: MCU1 : (SPI1 Master) <------> (SPI2 Slave): MCU2: USART2 ------> Terminal2
//***************************************************************************************


void clock_init()
{
	// Enable Clock for GPIO
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();

	// Enable Clock for AFIO
	RCC_AFIO_CLK_EN();
}

unsigned short ch;


void My_SPI1_IRQ_Callback(struct S_IRQ_SRC irq_src)
{
#ifdef MCU_Act_As_Slave
	if(irq_src.RXNE)
	{
		ch = 0xf;
		MCAL_SPI_TX_RX(SPI1, &ch, Pollingenable);
		MCAL_UART_SendData(USART1, &ch, enable);
	}

#endif
}



void UART_IRQ_Callback(void)
{
#ifdef MCU_Act_As_Master
	MCAL_UART_ReceiveData(USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);

	//send SPI
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 0);
	MCAL_SPI_TX_RX(SPI1, &ch, Pollingenable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);
#endif
}

int main(void)
{

	UART_Config uartCFG ;
	GPIO_PinConfig_t PinCfg;

	clock_init();


	//*************************UART INIT****************************

	//PA9 		TX
	//PA10 		RX
	//PA11		CTS
	//PA12		RTS
	uartCFG.BaudRate = UART_BaudRate_115200;
	uartCFG.HwFlowCtl = UART_HwFlowCtl_NONE;

	uartCFG.IRQ_Enable = UART_IRQ_Enable_RXNEIE;

	uartCFG.P_IRQ_CallBack = UART_IRQ_Callback;

	uartCFG.Parity = UART_Parity_NONE;
	uartCFG.Payload_Length = UART_Payload_Length_8B;
	uartCFG.StopBits = UART_StopBits_1;
	uartCFG.USART_Mode = UART_Mode_TX_RX;

	MCAL_UART_Init(USART1, &uartCFG);
	MCAL_UART_GPIO_Set_Pins(USART1);




	//*************************SPI INIT*************************

	//PA4 		SPI1 NSS
	//PA5 		SPI SCK
	//PA6		SPI MISO
	//PA7		SPI MOSI

	SPI_Config SPI1Cfg;

	SPI1Cfg.ClkPhase = SPI_Clock_Phase_2EDGE_first_data_capture_edge;
	SPI1Cfg.ClkPolarity = SPI_ClkPolarity_HIGH_when_idle;
	SPI1Cfg.DataSize = SPI_DataSize_8BIT;
	SPI1Cfg.Frame_Format = SPI_Frame_Format_MSB_transmitted_first;

	SPI1Cfg.SPI_BAUDRATEPRESCALER = SPI_BAUDRATEPRESCALER_8;
	SPI1Cfg.Communication_Mode = SPI_DIRECTION_2LINES;

#ifdef MCU_Act_As_Master
	SPI1Cfg.Device_Mode = SPI_Device_Mode_Master;
	SPI1Cfg.IRQ_Enable = SPI_IRQ_Enable_None;
	SPI1Cfg.NSS = SPI_NSS_Soft_NSSInternalSoft_Set;
	SPI1Cfg.P_IRQ_CallBack = NULL;


	// Configure SS on port A pin 4 by gpio
	PinCfg.GPIO_PinNumber = GPIO_PIN_4;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	//IDEL HIGH
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);

#endif

#ifdef MCU_Act_As_Slave
	SPI1Cfg.Device_Mode = SPI_Device_Mode_Slave;
	SPI1Cfg.IRQ_Enable = SPI_IRQ_Enable_RXNEIE;
	SPI1Cfg.NSS = SPI_NSS_Hard_Slave;
	SPI1Cfg.P_IRQ_CallBack = My_SPI1_IRQ_Callback;
#endif
	MCAL_SPI_Init(SPI1, &SPI1Cfg);
	MCAL_SPI_GPIO_Set_Pins(SPI1);

	while(1)
	{

	}
}
